---
kind: pipeline
type: docker
name: Default

steps:
  - name: Restore Cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.pnpm-store

  - name: Install Dependencies
    image: node:current-bullseye
    commands:
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
      - pnpm config set store-dir .pnpm-store
      - pnpm install
    depends_on:
      - Restore Cache

  - name: Test & Build
    image: node:current-bullseye
    commands:
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
      - pnpm test
      - pnpm build
    depends_on:
      - Install Dependencies

  - name: Deploy
    image: node:current-bullseye
    commands:
      - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
      - echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> .npmrc
      - echo email=hello@alca.dev >> .npmrc
      - echo always-auth=true >> .npmrc
      - pnpm run release
    when:
      event:
        - tag
    depends_on:
      - Test & Build
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN

  - name: Rebuild Cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.pnpm-store
    depends_on:
      - Install Dependencies

volumes:
  - name: cache
    host:
      path: /tmp/cache
