---
kind: pipeline
type: docker
name: Default

platform:
  os: linux
  arch: amd64

steps:
  - name: Restore Cache
    image: drillster/drone-volume-cache
    volumes:
      - name: ci-cache
        path: /ci-cache
    settings:
      restore: true
      mount:
        - ./.pnpm-store

  - name: Install Dependencies
    image: node:lts-bullseye
    commands:
      - npm install -g pnpm
      - pnpm config set store-dir .pnpm-store
      - pnpm install
    depends_on:
      - Restore Cache

  - name: Test & Build
    image: node:lts-bullseye
    commands:
      - apt update > /dev/null && apt -y install libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0 > /dev/null
      - npm install -g pnpm
      - pnpm build
      - pnpm test:e2e
    depends_on:
      - Install Dependencies

  - name: Rebuild Cache
    image: drillster/drone-volume-cache
    volumes:
      - name: ci-cache
        path: /ci-cache
    settings:
      rebuild: true
      mount:
        - ./.pnpm-store
    depends_on:
      - Install Dependencies

volumes:
  - name: ci-cache
    host:
      path: /tmp/ci-cache
